version: 2.1


jobs:

  build-frontend:
      executor: node
      steps:
        - checkout
        - attach_workspace:
            at: .
        - run:
            name: npm run build
            working_directory: ./frontend
            command: npm run build

  build-backend:
      executor: node
      steps:
        - checkout
        - attach_workspace:
            at: .
        - run:
            name: npm run build
            working_directory: ./backend
            command: npm run build
        - persist_to_workspace:
            root: .
            paths:
              - backend/dist

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
          